version: "3.9"
services:
    api:
        build: .
        restart: "always"
        container_name: "market-api"
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: "postgres:13-alpine"
        container_name: "market-database"
        restart: "always"
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: "market"

volumes:
    db:
